CREATE TABLE phones (
    id INT PRIMARY KEY,
    modelo VARCHAR(50),
    mac_address INT UNIQUE,
    fecha_fabricacion VARCHAR(50)
);

-- En el primer intento falla por el tipo de dato que tiene mac_address
INSERT INTO phones (id, modelo, mac_address, fecha_fabricacion) VALUES
(1, 'Iphone 14', '1B:2A:3C:4D:5F:6G', '2022-09-09');

ALTER TABLE phones
ALTER COLUMN mac_address TYPE VARCHAR(50);

INSERT INTO phones (id, modelo, mac_address, fecha_fabricacion) VALUES
(1, 'Iphone 14', '1B:2A:3C:4D:5F:6G', '2022-09-09');

ALTER TABLE phones
ALTER COLUMN mac_address SET NOT NULL;

INSERT INTO phones (id, modelo, mac_address, fecha_fabricacion) VALUES
(2, 'Iphone 13', '5B:1A:2C:7D:8F:7H', '2021-09-24');

SELECT * FROM phones;

TRUNCATE TABLE phones;

DROP TABLE phones;

---

ALTER TABLE phones
ADD COLUMN memoria_interna VARCHAR(20) NOT NULL,
ADD COLUMN memoria_ram VARCHAR(20) NOT NULL,
ADD COLUMN peso NUMERIC(5, 2) NOT NULL,
ADD COLUMN dimensiones VARCHAR(50) NOT NULL;

ALTER TABLE phones
ALTER COLUMN id ADD GENERATED BY DEFAULT AS IDENTITY;

INSERT INTO phones (modelo, mac_address, fecha_fabricacion, memoria_interna, memoria_ram, peso, dimensiones) VALUES
('Galaxy S26', 'AA:BB:CC:DD:EE:FF', '2023-01-15', '256GB', '8GB', 168.00, '146.3 x 70.9 x 7.6 mm');

INSERT INTO phones (modelo, mac_address, fecha_fabricacion, memoria_interna, memoria_ram, peso, dimensiones) VALUES
('Galaxy S26', 'AA:B2:CC:DD:EE:FF', '2023-01-15', '256GB', '8GB', 168.00, '146.3 x 70.9 x 7.6 mm');

SELECT * FROM phones;